use super::{
    AppText, BuildInfoText, Catalog, CliText, GuiText, ModelText, SystemText, UpdaterText,
};

pub(super) const CATALOG: Catalog = Catalog {
    gui: GuiText {
        check_updates: "Check for updates",
        update_selected: "Update selected",
        update_all: "Update all",
        cancel: "Cancel",
        elevate: "Restart as administrator",
        wait_operation: "Wait for the current operation to finish",
        restart_as_admin: "Restart the application with administrator privileges",
        auto_yes_toolbar: "Automatically confirm updates (-y)",
        tab_overview: "Overview",
        tab_modules: "Modules",
        tab_logs: "Logs",
        tab_settings: "Settings",
        selected_modules_counter: "Selected modules: {selected}/{total}",
        modules_with_updates_counter: "With updates: {updates}/{total}",
        overview_title: "Summary",
        found_modules: "Modules found: {count}",
        selected_count: "Selected: {count}",
        need_updates_count: "Need updates: {count}",
        logs_accumulated: "Log entries: {count}",
        overview_instructions: "Use Modules to select packages and Logs to view progress and errors.",
        empty_modules: "No modules found. Click Check for updates.",
        empty_visible_modules: "No modules to display. Enable Show unavailable modules in Settings or scan again.",
        export_logs: "Export logs",
        module_count: "Modules: {count}",
        record_count: "Entries: {count}",
        logs_empty: "No logs yet",
        settings_title: "Settings",
        auto_yes_setting: "Automatically confirm updates (-y)",
        show_not_found: "Show unavailable modules",
        show_up_to_date: "Show up-to-date modules",
        settings_saved: "Selected modules and display settings are saved between sessions.",
        language_label: "Language",
        language_changed: "Language changed to {language}",
        version: "Version: {value}",
        commit: "Commit: {value}",
        dirty: "Working tree changes: {value}",
        build_details: "Build details",
        elevation_warning: "Running without administrator privileges: system package managers may be unavailable",
        selection_menu: "Module selection",
        select_visible: "Select all visible",
        deselect_visible: "Deselect all visible",
        invert_selection: "Invert selection",
        select_only_updates: "Select modules with updates",
        status_waiting: "Waiting to start",
        status_scanning: "Scanning...",
        log_scan_started: "Update scan started",
        status_updating: "Updating...",
        summary_update_cancelled: "Update cancelled",
        summary_no_selected_updates: "No selected modules have available updates",
        summary_update_success: "Update completed successfully",
        summary_update_errors: "Update completed with errors",
        status_cancel_requested: "Cancellation requested; stopping update processes...",
        log_cancel_requested: "Cancellation requested; stopping update processes. No new modules will be started.",
        status_cancel_incomplete: "Cancellation requested, but some processes could not be stopped",
        log_cancel_error: "Cancellation error: {error}",
        status_no_elevated_modules: "No modules require elevated privileges",
        error_save_scan_results: "Could not save scan results: {error}",
        status_request_elevation: "Requesting elevated privileges...",
        status_scan_progress: "Scanning: checked {completed}/{total}",
        status_scan_complete: "Scan complete. Module count: {modules}; available update count: {updates}",
        status_elevated_success: "Restarted with elevated privileges",
        error_elevate: "Could not elevate privileges: {error}",
        error_prefix: "Error: {error}",
        status_update_prefix: "Update status: {status}",
        selected_packages_count: "Selected packages: {selected}/{total}",
        update_details: "Details ({count})",
        full_system_update_notice: "Full-system update; packages found: {count}",
        logs_copied: "Logs copied to the clipboard as JSON",
        error_export_logs: "Could not prepare logs for export: {error}",
        error_save_state: "Could not save GUI state: {error}",
        error_config_directory: "Could not determine the configuration directory",
    },
    model: ModelText {
        kind_system: "System",
        kind_tool: "Tool",
        kind_python: "Python",
        status_not_found: "Not installed",
        status_up_to_date: "Up to date",
        status_updates_available: "Updates available: {count}",
        status_error: "Error: {message}",
        status_windows_updates: "Available updates: {count}. Install them through Windows Update",
        status_empty_updates: "No individual updates to display",
        scope_node_self_update: "self-update",
    },
    app: AppText {
        phase_queued: "Queued",
        phase_running: "Running",
        phase_completed: "Completed",
        phase_failed: "Error",
        phase_cancelled: "Cancelled",
        table_tool: "Tool",
        table_installed: "Installed",
        table_status: "Status",
        table_updates: "Updates",
        yes: "Yes",
        no: "No",
        full_update: "Full-system update (package count: {packages})",
        elevation_warning: "Running without administrator privileges: system package managers may be skipped or fail",
        skip_prefix: "Skipped: {reason}",
        updater_not_found: "{module}: updater not found",
        stage_error: "Stage: error: {error}",
        stage_start: "Stage: starting update",
        stage_cancelled: "Stage: cancelled",
        stage_completed: "Stage: completed",
        stage_cancelled_before_start: "Stage: cancelled before start",
        update_not_verified: "Update was not confirmed by a follow-up check; still available: {updates}",
        skip_not_selected: "module not selected",
        skip_not_installed: "tool is not installed",
        skip_no_updates: "no updates required",
        skip_all_unselected: "all package updates in this module are deselected",
    },
    updater: UpdaterText {
        invalid_package_name: "{manager}: invalid selected package name `{package}`",
        command_spawn_error: "Failed to start command `{program}`: {error}",
        command_stream_error: "Failed to read command output for `{program}`: {error}",
        command_failed: "Command `{program}` exited with code {code}: {stderr}",
        json_error: "JSON error: {error}",
        http_error: "HTTP error: {error}",
        create_http_client_error: "Could not create HTTP client: {error}",
        command_stdout_unavailable: "{program}: stdout is unavailable",
        command_stderr_unavailable: "{program}: stderr is unavailable",
        command_stdout_thread_failed: "{program}: stdout reader thread panicked",
        command_stderr_thread_failed: "{program}: stderr reader thread panicked",
        process_tree_termination_failed: "Could not terminate process tree {process_id}: {error}",
        taskkill_failed: "taskkill exited with code {code}: {details}",
        process_termination_unsupported: "Process-tree termination is not supported on this platform",
        powershell_missing: "PowerShell was not found",
        windows_update_summary: "Windows Update: available update count: {count}. Automatic installation is disabled; open Settings -> Windows Update to install them manually.",
        winget_package_update_failed: "winget: failed to update package `{package}`: {reason}",
        winget_packages_update_failed: "winget: package update failures ({count}): {errors}",
        winget_download_timeout: "The download timed out (0x80072EE2); check the connection, proxy, and download URL, then retry `winget upgrade --id {package_id} --exact`",
        winget_install_method_changed: "The installation method for the new version differs from the installed version; run `winget uninstall --id {package_id} --exact`, then `winget install --id {package_id} --exact`",
        command_exit_code_with_output: "{output} (exit code {code})",
        command_exit_code: "exit code {code}",
        pacman_no_details: "pacman did not provide details",
        apt_get_refreshing: "apt-get: refreshing package indexes",
        selected_update_mode: "using `{subcommand}` update mode",
        updating_selected_packages: "updating selected packages only",
        python_missing: "python was not found",
        pip_list_failed_fallback: "pip: could not list packages using python -m pip ({error}); trying uv",
        pip_update_failed_fallback: "pip: update using python -m pip failed ({error}); trying uv",
        pip_updates_not_found: "pip: no updates found",
        uv_updates_not_found: "uv: no updates found",
        uv_current_version_unknown: "uv: could not determine the current version",
        npm_updates_not_found: "npm: no updates found",
        pnpm_updates_not_found: "pnpm: no updates found",
        node_updates_not_found: "node: no updates found",
        node_release_index_invalid_json: "node: could not parse the official release index from {url} (Content-Type: {content_type}): {error}. Check your connection or proxy.",
        node_official_version_missing: "node: the official site did not return the latest version",
        node_nvm_version_invalid: "node: nvm returned an invalid default version",
        node_current_version_unknown: "node: could not determine the current version",
        node_install_method: "node: detected installation method: {method}",
        node_install_method_unknown: "node: could not detect the installation method; update Node.js manually using its original package manager or the official installer",
        node_nvm_command_missing: "node: command for nvm was not found",
        node_nvm_script_missing: "node: nvm was detected, but nvm.sh was not found; set NVM_DIR or check the node path",
        node_nvm_script_invalid: "node: invalid path to nvm.sh",
        node_bash_required: "node: bash is required to run nvm.sh",
        node_official_msi: "official MSI",
        unknown: "unknown",
        node_msi_unsupported_arch: "node: the official MSI does not support architecture {architecture}",
        node_downloading_installer: "node: downloading the official installer {url}",
        node_create_file_failed: "node: could not create {path}: {error}",
        node_save_file_failed: "node: could not save {path}: {error}",
        package_manager_version_unknown: "{program}: could not determine the current version",
        npm_registry_latest_missing: "{program}: the npm registry did not return the latest version",
        editor_extension_update_failed: "{program}: failed to update extension `{extension}`: {error}",
        editor_extensions_update_failed: "{program}: extension update failures ({count}): {errors}",
        editor_command_missing: "{program}: editor command was not found",
    },
    system: SystemText {
        temp_file_missing_parent: "Temporary file has no parent directory",
        temp_directory_unknown: "Could not determine the system temporary directory",
        temp_directory_check_failed: "Could not verify the temporary-file directory",
        temp_file_outside_directory: "Temporary file is outside the system temporary directory",
        temp_file_name_invalid: "Invalid temporary-file name",
        temp_file_name_unexpected: "Unexpected temporary-file name",
        temp_file_identity_invalid: "Invalid temporary-file identifier",
        temp_file_pid_invalid: "Invalid process ID in temporary-file name",
        temp_file_nonce_invalid: "Invalid nonce in temporary-file name",
        temp_file_missing: "Temporary file does not exist",
        temp_file_not_regular: "Temporary path is not a regular file",
        temp_file_already_used: "Temporary marker has already been used",
        already_elevated: "Application is already running with elevated privileges",
        no_modules_to_rescan: "No modules were specified for rescanning",
        executable_path_unknown: "Could not determine the executable path",
        windows_elevation_denied: "Windows denied the request to run as administrator (code {code})",
        pkexec_missing: "pkexec was not found; install PolicyKit to launch the GUI as root",
        system_time_unknown: "Could not determine the system time",
        ready_marker_create_failed: "Could not create the GUI startup marker",
        pkexec_start_failed: "Could not start pkexec",
        elevated_launch_check_failed: "Could not check whether the application started as root",
        elevated_window_failed: "The new window did not start with root privileges (code {code})",
        elevation_unsupported: "Restarting with elevated privileges is supported only on Windows and Linux",
    },
    cli: CliText {
        unknown_modules: "Unknown module names: {unknown}. Available names: {available}",
        update_worker_panicked: "Update worker thread panicked",
    },
    build_info: BuildInfoText {
        application: "Application",
        version: "Version",
        profile: "Profile",
        git: "Git",
        branch: "Branch",
        commit_time: "Commit time",
        dirty: "Working tree changes",
        compiler: "Compiler",
        rust_version: "Rust version",
        optimization: "Optimization level",
        debug_info: "Debug information",
        target_platform: "Target platform",
        target: "Target",
        host: "Host",
    },
};
