use super::{
    AppText, BuildInfoText, Catalog, CliText, GuiText, ModelText, SystemText, UpdaterText,
};

pub(super) const CATALOG: Catalog = Catalog {
    gui: GuiText {
        check_updates: "Проверить обновления",
        update_selected: "Обновить выбранное",
        update_all: "Обновить всё",
        cancel: "Отменить",
        elevate: "Перезапустить от имени администратора",
        wait_operation: "Дождитесь завершения текущей операции",
        restart_as_admin: "Перезапустить приложение с правами администратора",
        auto_yes_toolbar: "Автоматически подтверждать обновления (-y)",
        tab_overview: "Обзор",
        tab_modules: "Модули",
        tab_logs: "Журналы",
        tab_settings: "Настройки",
        selected_modules_counter: "Выбрано модулей: {selected}/{total}",
        modules_with_updates_counter: "С обновлениями: {updates}/{total}",
        overview_title: "Сводка",
        found_modules: "Найдено модулей: {count}",
        selected_count: "Выбрано: {count}",
        need_updates_count: "Требуют обновления: {count}",
        logs_accumulated: "Записей в журнале: {count}",
        overview_instructions: "Выберите пакеты во вкладке «Модули», а ход выполнения и ошибки смотрите в разделе «Журналы».",
        empty_modules: "Список модулей пуст. Нажмите «Проверить обновления».",
        empty_visible_modules: "Нет отображаемых модулей. Включите показ недоступных модулей в настройках или выполните сканирование.",
        export_logs: "Экспортировать журналы",
        module_count: "Модулей: {count}",
        record_count: "Записей: {count}",
        logs_empty: "Журнал пока пуст",
        settings_title: "Настройки",
        auto_yes_setting: "Автоматически подтверждать обновления (-y)",
        show_not_found: "Показывать недоступные модули",
        show_up_to_date: "Показывать актуальные модули",
        settings_saved: "Выбор модулей и параметры отображения сохраняются между запусками.",
        language_label: "Язык",
        language_changed: "Язык изменён на {language}",
        version: "Версия: {value}",
        commit: "Коммит: {value}",
        dirty: "Изменения в рабочей копии: {value}",
        build_details: "Информация о сборке",
        elevation_warning: "Приложение запущено без прав администратора: системные менеджеры пакетов могут быть недоступны",
        selection_menu: "Выбор модулей",
        select_visible: "Выбрать все видимые",
        deselect_visible: "Снять выбор со всех видимых",
        invert_selection: "Инвертировать выбор",
        select_only_updates: "Выбрать модули с обновлениями",
        status_waiting: "Ожидание запуска",
        status_scanning: "Сканирование...",
        log_scan_started: "Начата проверка обновлений",
        status_updating: "Выполняется обновление...",
        summary_update_cancelled: "Обновление отменено",
        summary_no_selected_updates: "Нет выбранных модулей с доступными обновлениями",
        summary_update_success: "Обновление успешно завершено",
        summary_update_errors: "Обновление завершено с ошибками",
        status_cancel_requested: "Запрошена отмена: завершаются процессы обновления...",
        log_cancel_requested: "Запрошена отмена; процессы обновления завершаются. Новые модули запускаться не будут.",
        status_cancel_incomplete: "Запрошена отмена, но не все процессы удалось остановить",
        log_cancel_error: "Ошибка отмены: {error}",
        status_no_elevated_modules: "Нет модулей, требующих повышенных прав",
        error_save_scan_results: "Не удалось сохранить результаты сканирования: {error}",
        status_request_elevation: "Запрос повышенных прав...",
        status_scan_progress: "Сканирование: проверено {completed}/{total}",
        status_scan_complete: "Проверка завершена. Количество модулей: {modules}; количество доступных обновлений: {updates}",
        status_elevated_success: "Приложение перезапущено с повышенными правами",
        error_elevate: "Не удалось повысить права: {error}",
        error_prefix: "Ошибка: {error}",
        status_update_prefix: "Статус обновления: {status}",
        selected_packages_count: "Выбрано пакетов: {selected}/{total}",
        update_details: "Подробности ({count})",
        full_system_update_notice: "Полное обновление системы; найдено пакетов: {count}",
        logs_copied: "Журналы скопированы в буфер обмена в формате JSON",
        error_export_logs: "Не удалось подготовить журналы к экспорту: {error}",
        error_save_state: "Не удалось сохранить состояние GUI: {error}",
        error_config_directory: "Не удалось определить каталог конфигурации",
    },
    model: ModelText {
        kind_system: "Системный",
        kind_tool: "Инструмент",
        kind_python: "Python",
        status_not_found: "Не установлен",
        status_up_to_date: "Актуален",
        status_updates_available: "Доступно обновлений: {count}",
        status_error: "Ошибка: {message}",
        status_windows_updates: "Доступно обновлений: {count}. Установите их через Центр обновления Windows",
        status_empty_updates: "Нет отдельных обновлений для отображения",
        scope_node_self_update: "самообновление",
    },
    app: AppText {
        phase_queued: "В очереди",
        phase_running: "Выполняется",
        phase_completed: "Завершено",
        phase_failed: "Ошибка",
        phase_cancelled: "Отменено",
        table_tool: "Инструмент",
        table_installed: "Установлен",
        table_status: "Статус",
        table_updates: "Обновления",
        yes: "Да",
        no: "Нет",
        full_update: "Полное обновление системы (количество пакетов: {packages})",
        elevation_warning: "Приложение запущено без прав администратора: системные менеджеры пакетов могут быть пропущены или завершиться с ошибкой",
        skip_prefix: "Пропуск: {reason}",
        updater_not_found: "{module}: обработчик обновления не найден",
        stage_error: "Этап: ошибка: {error}",
        stage_start: "Этап: запуск обновления",
        stage_cancelled: "Этап: отменено",
        stage_completed: "Этап: завершено",
        stage_cancelled_before_start: "Этап: отменено до запуска",
        update_not_verified: "Повторная проверка не подтвердила обновление; всё ещё доступны: {updates}",
        skip_not_selected: "модуль не выбран",
        skip_not_installed: "инструмент не установлен",
        skip_no_updates: "обновления не требуются",
        skip_all_unselected: "все обновления пакетов в этом модуле сняты с выбора",
    },
    updater: UpdaterText {
        invalid_package_name: "{manager}: некорректное имя выбранного пакета `{package}`",
        command_spawn_error: "Не удалось запустить команду `{program}`: {error}",
        command_stream_error: "Не удалось прочитать вывод команды `{program}`: {error}",
        command_failed: "Команда `{program}` завершилась с кодом {code}: {stderr}",
        json_error: "Ошибка JSON: {error}",
        http_error: "Ошибка HTTP: {error}",
        create_http_client_error: "Не удалось создать HTTP-клиент: {error}",
        command_stdout_unavailable: "{program}: stdout недоступен",
        command_stderr_unavailable: "{program}: stderr недоступен",
        command_stdout_thread_failed: "{program}: поток чтения stdout завершился с ошибкой",
        command_stderr_thread_failed: "{program}: поток чтения stderr завершился с ошибкой",
        process_tree_termination_failed: "Не удалось завершить дерево процесса {process_id}: {error}",
        taskkill_failed: "taskkill завершился с кодом {code}: {details}",
        process_termination_unsupported: "Завершение дерева процессов не поддерживается на этой платформе",
        powershell_missing: "PowerShell не найден",
        windows_update_summary: "Центр обновления Windows: количество доступных обновлений: {count}. Автоматическая установка отключена; откройте Параметры -> Центр обновления Windows и запустите обновление вручную.",
        winget_package_update_failed: "winget: не удалось обновить пакет `{package}`: {reason}",
        winget_packages_update_failed: "winget: ошибки обновления пакетов ({count}): {errors}",
        winget_download_timeout: "Истекло время ожидания загрузки (0x80072EE2); проверьте соединение, прокси и адрес загрузки, затем повторите `winget upgrade --id {package_id} --exact`",
        winget_install_method_changed: "Способ установки новой версии отличается от установленного; выполните `winget uninstall --id {package_id} --exact`, затем `winget install --id {package_id} --exact`",
        command_exit_code_with_output: "{output} (код завершения {code})",
        command_exit_code: "код завершения {code}",
        pacman_no_details: "pacman не сообщил подробностей",
        apt_get_refreshing: "apt-get: обновление индексов пакетов",
        selected_update_mode: "выбран режим обновления `{subcommand}`",
        updating_selected_packages: "обновляются только выбранные пакеты",
        python_missing: "python не найден",
        pip_list_failed_fallback: "pip: не удалось получить список пакетов через python -m pip ({error}); пробую uv",
        pip_update_failed_fallback: "pip: обновление через python -m pip завершилось ошибкой ({error}); пробую uv",
        pip_updates_not_found: "pip: обновления не найдены",
        uv_updates_not_found: "uv: обновления не найдены",
        uv_current_version_unknown: "uv: не удалось определить текущую версию",
        npm_updates_not_found: "npm: обновления не найдены",
        pnpm_updates_not_found: "pnpm: обновления не найдены",
        node_updates_not_found: "node: обновления не найдены",
        node_release_index_invalid_json: "node: не удалось разобрать официальный индекс релизов с {url} (Content-Type: {content_type}): {error}. Проверьте подключение или прокси.",
        node_official_version_missing: "node: официальный сайт не вернул последнюю версию",
        node_nvm_version_invalid: "node: nvm вернул некорректную версию default",
        node_current_version_unknown: "node: не удалось определить текущую версию",
        node_install_method: "node: определён способ установки: {method}",
        node_install_method_unknown: "node: не удалось определить способ установки; обновите Node.js вручную через исходный менеджер пакетов или официальный установщик",
        node_nvm_command_missing: "node: команда nvm не найдена",
        node_nvm_script_missing: "node: обнаружен nvm, но не найден его скрипт nvm.sh; задайте NVM_DIR или проверьте путь node",
        node_nvm_script_invalid: "node: некорректный путь к nvm.sh",
        node_bash_required: "node: для запуска nvm.sh требуется bash",
        node_official_msi: "официальный MSI",
        unknown: "неизвестен",
        node_msi_unsupported_arch: "node: официальный MSI не поддерживает архитектуру {architecture}",
        node_downloading_installer: "node: загрузка официального установщика {url}",
        node_create_file_failed: "node: не удалось создать {path}: {error}",
        node_save_file_failed: "node: не удалось сохранить {path}: {error}",
        package_manager_version_unknown: "{program}: не удалось определить текущую версию",
        npm_registry_latest_missing: "{program}: npm registry не вернул последнюю версию",
        editor_extension_update_failed: "{program}: не удалось обновить расширение `{extension}`: {error}",
        editor_extensions_update_failed: "{program}: ошибки обновления расширений ({count}): {errors}",
        editor_command_missing: "{program}: команда редактора не найдена",
    },
    system: SystemText {
        temp_file_missing_parent: "У служебного файла отсутствует родительский каталог",
        temp_directory_unknown: "Не удалось определить системный временный каталог",
        temp_directory_check_failed: "Не удалось проверить каталог служебного файла",
        temp_file_outside_directory: "Служебный файл находится вне системного временного каталога",
        temp_file_name_invalid: "Некорректное имя служебного файла",
        temp_file_name_unexpected: "Неожиданное имя служебного файла",
        temp_file_identity_invalid: "Некорректный идентификатор служебного файла",
        temp_file_pid_invalid: "Некорректный PID в имени служебного файла",
        temp_file_nonce_invalid: "Некорректный nonce в имени служебного файла",
        temp_file_missing: "Служебный файл не существует",
        temp_file_not_regular: "Служебный путь не является обычным файлом",
        temp_file_already_used: "Служебный маркер уже был использован",
        already_elevated: "Приложение уже запущено с повышенными правами",
        no_modules_to_rescan: "Не указаны модули для повторного сканирования",
        executable_path_unknown: "Не удалось определить путь к исполняемому файлу",
        windows_elevation_denied: "Windows отклонила запуск с правами администратора (код {code})",
        pkexec_missing: "pkexec не найден; установите PolicyKit для запуска GUI с правами root",
        system_time_unknown: "Не удалось определить системное время",
        ready_marker_create_failed: "Не удалось создать маркер запуска GUI",
        pkexec_start_failed: "Не удалось запустить pkexec",
        elevated_launch_check_failed: "Не удалось проверить запуск приложения с правами root",
        elevated_window_failed: "Новое окно с правами root не запустилось (код {code})",
        elevation_unsupported: "Перезапуск с повышенными правами поддерживается только в Windows и Linux",
    },
    cli: CliText {
        unknown_modules: "Неизвестные имена модулей: {unknown}. Доступные имена: {available}",
        update_worker_panicked: "Поток обновления завершился аварийно",
    },
    build_info: BuildInfoText {
        application: "Приложение",
        version: "Версия",
        profile: "Профиль",
        git: "Git",
        branch: "Ветка",
        commit_time: "Время коммита",
        dirty: "Изменения в рабочей копии",
        compiler: "Компилятор",
        rust_version: "Версия Rust",
        optimization: "Уровень оптимизации",
        debug_info: "Отладочная информация",
        target_platform: "Целевая платформа",
        target: "Target",
        host: "Host",
    },
};
